### ISSUE TITLE
 usb_cam cannot  be install 

### ISSUE THREAD

**Issue by guan4286** [ros-drivers/usb_cam#101]
g@g-System-Product-Name:~$ sudo apt-get install ros-kinetic-usb-cam
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ros-kinetic-usb-cam : Depends: v4l-utils but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by guan4286** [comment]
what is v4l-utils and how to install it

**Comment by ouyangmeizi** [comment]
I have the same problem now, so have you solve this and can you help me ? thanks !

**Comment by Sumyer** [comment]
you can run this command to install v4l-utils:
sudo apt-get install v4l-utils

**Comment by twdragon** [comment]
Closed due to inactivity
