### ISSUE TITLE
roslaunch usb_cam usb_cam-test.launch,the cam window is weird

### ISSUE THREAD

**Issue by Lee-xiao** [ros-drivers/usb_cam#102]
I tried to open the cam in the ROS ,and I input the following instruction in the terminal：
          roslaunch usb_cam usb_cam-test.launch
but my cam window show like following:
![image](https://user-images.githubusercontent.com/34397296/47157450-ee46df80-d31b-11e8-9009-18da5510ecac.png)
What should I do?

**Comment by PatronusCoder** [comment]
If you are using "pixel_format" as "yuyv", try changing it to "mjpeg" or the other way around. For me, it worked with the first method.

**Comment by nana400** [comment]
I have the same result as yours.. and when I have changed the "pixel_format" to "mjpeg"  I/ve got this result
[https://imgur.com/zHxN3Q9](url)

**Comment by TheLoneFedora** [comment]
I'm a Grad student who has taken over someone else's project with limited documentation.  I'm very new to Ubuntu, GitHub, etc.  Same problem.  How do I change the pixel_format?

**Comment by nana400** [comment]
Just go to the launch file and change the line from "<param
name="pixel_format" value="yuyv" />" to "<param name="pixel_format"
value="mjpeg" />"

**Comment by TheLoneFedora** [comment]
Thank you nana400.  First, I should have clarified my edit to my post.  I did figure out where to change the pixel format.  However, playing with that feature did not resolve the underlying green screen issues; I was having the same issues as the original poster, despite trying other pixel values.

**Comment by TheLoneFedora** [comment]
RESOLUTION:
I did get past the green screen of death.  For me at least it came down to 3 aspects of the launch file I was using.
i)   node name='usb_camera' ….> failed for some reason, but <node name='usb_cam' ….> does not.
ii)  <param name="video_device"  value="/dev/video1" /> is apparently trying to reference the laptop built-in camera.  Changing to <… value="/dev/video0" /> is apparently the correct input for the Boson FLIR camera I am using
iii) <remap from="/output/image_raw" to="camera/image_raw"/> fails.  But <… to="/usb_cam/image_raw"/> succeeds


I found these solutions once I figured out that another launch file on the computer usb_cam-test.launch was working.  Trial-and-error ferreted out the problem code.  I hope this helps your troubleshooting.

**Comment by QiHanY** [comment]
> I have the same result as yours.. and when I have changed the "pixel_format" to "mjpeg" I've got this error..
> 
> [ERROR] [1547486033.596328143]: outbuf size mismatch. pic_size: 460800 bufsize: 614400
> [ERROR] [1547486033.631609438]: outbuf size mismatch. pic_size: 460800 bufsize: 614400
> [ERROR] [1547486033.666822355]: outbuf size mismatch. pic_size: 460800 bufsize: 614400
> [ERROR] [1547486033.694541910]: outbuf size mismatch. pic_size: 460800 bufsize: 614400
> [ERROR] [1547486033.729776569]: outbuf size mismatch. pic_size: 460800 bufsize: 614400
> [ERROR] [1547486033.779654260]: outbuf size mismatch. pic_size: 460800 bufsize: 614400
> any help please??

hello ? I meet the same problems ,do you have any answer?

**Comment by Adharshmahesh** [comment]
Hi, I have the exact same problems. Is there any solution to this?
