### ISSUE TITLE
ros2 version

### ISSUE THREAD

**Issue by lucasw** [ros-drivers/usb_cam#103]
I'm going to make a ros2 version (unless someone else already has?  I spot checked a few forks but didn't see one)- it looks like the separation between ros1 node and usb cam code is mostly clean, there are just ROS_ERROR_STREAMS to convert.

https://github.com/lucasw/usb_cam/tree/bouncy

**Comment by lucasw** [comment]
The ros2 branch is working in bouncy but the frame grabbing is very slow, I need to look into that.  The setting of camera parameters live is offloaded to https://github.com/lucasw/v4l2ucp/tree/ros2

**Comment by sgvandijk** [comment]
I had started work on this separately, before coming across this issue and your fork. IMHO it started diverging a bit from the original version, with some good things but maybe can be done in further iterations? So I pushed my version up as a PR to take the discussion further.

**Comment by lucasw** [comment]
I didn't make a pr because there wasn't a bouncy or ros2 branch to merge into.  A git knowledgeable maintainer can do that after the pr, but this package is orphaned now- or even re-orphaned?  I think being a maintainer here is hard because any one person probably only has a small number of usb cameras to test changes with.

I tried to draw some attention to usb_cam in a discourse post https://discourse.ros.org/t/ros2-usb-cam-imgui-image-manipulation-nodes/6894/3 .
 
There are a lot of usb_cam branches with a lot of work done on them (though no other ros2 versions at least as of a month ago) https://github.com/ros-drivers/usb_cam/network , for most the authors didn't even bother with a pr because they wanted to rewrite so much of it- some of my changes parallel theirs.

**Comment by r7vme** [comment]
Hey, @lucasw @sgvandijk i'm also looking for usb_cam for ROS2.

Any chance to find maintainers and create ros2 branch?

**Comment by sgvandijk** [comment]
Hi @r7vme I have gone ahead and implemented a ROS 2 package from scratch: https://robocuplab.herts.ac.uk/boldhearts/ros2_v4l2_camera, it is still partly WIP, but it should be ready to be used and it would be great to get feedback from others who use other hardware from us :)

**Comment by Karsten1987** [comment]
@k-okada could you please push a `ros2` branch to this repo to enable @lucasw to open a PR? Thanks.

**Comment by k-okada** [comment]
@Karsten1987, @lucasw  Is https://github.com/ros-drivers/usb_cam/tree/ros2 ok for you?

**Comment by Karsten1987** [comment]
thanks a lot. @lucasw it would be great if you could open a PR towards that branch. Even though your initial work was for bouncy, we should be able to iterate over it online to make it work for Foxy.

**Comment by flynneva** [comment]
refer to the [`ros2` branch](https://github.com/ros-drivers/usb_cam/tree/ros2) on this repo for more!
