### ISSUE TITLE
Wrong format with ELP-USBFHD01M-L180

### ISSUE THREAD

**Issue by ghost** [ros-drivers/usb_cam#111]
I was running this ROS node with ELP-USBFHD01M-L180 using the launch file. However, I got the following error:

[ INFO] [1549254064.097680530]: Starting 'head_camera' (/dev/video0) at 640x480 via mmap (yuyv) at 30 FPS
[ERROR] [1549254064.108899052]: VIDIOC_S_FMT error 22, Invalid argument

Launch file pixel_format is yuyv
How can I fix it?

**Comment by twdragon** [comment]
Closed due to inactivity
