### ISSUE TITLE
Two ROS packages are needed for build

### ISSUE THREAD

**Issue by bigbellmercy** [ros-drivers/usb_cam#117]
I've found that two ROS packages are needed to be installed before building 'usb_cam' package. Otherwise, build error happens.

camera_calibration_parsers
camera_info_manager

They are provided at: https://github.com/ros-perception/image_common 

And one more linux package should be installed:

v4l2-ctl

After installing all the three packages, usb_cam works.

Such dependency information above would be better to be written in the Readme.md file.

**Comment by k-okada** [comment]
they should be installed by `rosdep install`
http://wiki.ros.org/ROS/Tutorials/rosdep /
http://wiki.ros.org/Installation/Source#melodic.2BAC8-Installation.2BAC8-Source.Installation
please try it
--
◉ Kei Okada



2019年9月26日(木) 2:01 Jong <notifications@github.com>:

**Comment by flynneva** [comment]
@bigbellmercy going to close this issue since it seems it was answered above. please comment here if you are still experiencing issues.
