### ISSUE TITLE
there are no response when I modify the value of brightness,white_balance,contrast

### ISSUE THREAD

**Issue by melodynk** [ros-drivers/usb_cam#121]
Hi author and everyone,
     I would like to change the camera's brightness,white_balance,contrast's value,in the usb_cam-test.launch file ,but there are no response when I modify them.How can I make a modification.Thanks!

     
![usb_cam](https://user-images.githubusercontent.com/37090372/71715613-f02b8e80-2e4c-11ea-97f5-6268af019f4b.png)

**Comment by flynneva** [comment]
@melodynk this works on the ROS 2 version of this package btw! Closing this issue since I also think it is working on the ROS 1 branch as well
