### ISSUE TITLE
usb_cam orphaned - offer to support

### ISSUE THREAD

**Issue by flynneva** [ros-drivers/usb_cam#135]
full post [made on ROS discourse](https://discourse.ros.org/t/usb-cam-orphaned-offer-to-support/19367) but i see this package has been orphaned and in dire need of someone to look at some of the open PR's/issues.

I'm offering to help out with this if someone just grants me rights to this repo.

**Comment by flynneva** [comment]
@k-okada it looks like you've pushed the most recent commit to this repo. is there any way you could add me as a maintainer?

**Comment by Karsten1987** [comment]
That's great news! Thanks @flynneva for picking this up. At least for the ROS2 part of it, I am happy to assist you as much as I can.

**Comment by flynneva** [comment]
fixed with #136

**Comment by 130s** [comment]
:champagne: 

Would @flynneva update [orphaned package list[(http://wiki.ros.org/OrphanedPackage) and remove usb_cam from there?
