### ISSUE TITLE
When I use USB to start the camera, the interface is green？

### ISSUE THREAD

**Issue by HerdGold3** [ros-drivers/usb_cam#161]
Hello, my computer is Ubuntu 16.04. The camera model is inter d435i
When I use the command: roslaunch USB_ Cam-test.launch starts the camera，the interface is green.

![green](https://user-images.githubusercontent.com/84887856/125402615-31f4a800-e3e7-11eb-9c26-134564ef098b.png)

Does anyone have the same problem as me? How is it solved?

**Comment by hxj0316** [comment]
Hello, I have encountered the same problem as you. Have you solved it?
![Screenshot_2021-08-12_18-41-58](https://user-images.githubusercontent.com/66103957/129298775-6a075a6a-34cb-49b6-a238-4976788da7cc.png)
![Screenshot_2021-08-12_18-44-22](https://user-images.githubusercontent.com/66103957/129298786-3c7a6328-da85-4d6d-bc44-d1a7e4d600c0.png)

**Comment by flynneva** [comment]
make sure you are setting your pixel formats correctly - it looks like you are trying to set the `yuyv` when your device doesnt support that format.

you can see the supported formats that are in the code here: https://github.com/ros-drivers/usb_cam/blob/3ce8ee1c47c03be37229bf5857ae9a309d8eb1e8/src/usb_cam.cpp#L1229

maybe try some different ones to see if one of them will match the supported versions you have for your device.

**Comment by hxj0316** [comment]
Hello, thank you for your reply, I am not using the usb_cam package, but ros2_v4l2_camera

**Comment by flynneva** [comment]
its the same problem though - you need to change the pixel format you are using

**Comment by hxj0316** [comment]
When I use usb_cam, it shows that the stream parameters cannot be set. Can you help me see the question I asked?

**Comment by HerdGold3** [comment]
Hi, I have solved my problem. I modified the parameters in the camera startup file and changed video0 to video3, because the camera I use has three camera parameters. The previous setting error causes the open camera not to be RGB, so the green interface is displayed.

**Comment by flynneva** [comment]
@hxj0316 glad you were able to solve your issue, is it ok to close this issue now?
