### ISSUE TITLE
[ROS2] generate some docs for usb_cam in ros2

### ISSUE THREAD

**Issue by flynneva** [ros-drivers/usb_cam#163]
1. [x] Add mkdocs config for this repo
2. [x] Add CI job to generate documentation for each PR
3. [x] Add doxygen -> doxybook2 -> mkdocs pipeline to generate API docs

**Comment by niranjanravilevelup** [comment]
Hi @flynneva , I am using the git repo: https://github.com/flynneva/usb_cam for ros2 foxy version. It works completely fine when I use a single USB camera. But I am unable to modify the **usb_cam_node_exe** file. I want to change the topic name for the second USB camera. Any ideas on how to achieve this?

**Comment by flynneva** [comment]
hi @niranjanravilevelup, you should be able to do this by remapping the namespace when you launch the node:

```
ros2 run usb_cam usb_cam_node_exe --remap __ns:=/usb_cam_left
ros2 run usb_cam usb_cam_node_exe --remap __ns:=/usb_cam_right
```

you'll need to load in different param files though I think to set the port `/dev/video0` and `/dev/video1` differently

**Comment by niranjanravilevelup** [comment]
@flynneva  Thank you. It was pretty helpful.

**Comment by flynneva** [comment]
@niranjanravilevelup  no worries! thank you for pointing out something else to add to the `README` - i added it there for others in to use in the future.

**Comment by flynneva** [comment]
Completed with #303
