### ISSUE TITLE
ROS2 中使用rviz2订阅image/raw显示No image

### ISSUE THREAD

**Issue by hxj0316** [ros-drivers/usb_cam#165]
你好，我在ubuntu20.04+ros foxy的环境下使用usb_cam来进行摄像头配置。我成功的编译并运行了软件包，但是我最后使用ros2 run usb_cam usb_cam_node显示No executable found，不过当我运行ros2 launch usb_cam demo_launch.py的时候，有画面出来了。同时在rviz2中也有/image_raw的topic，但是当我尝试订阅该话题时，却一直显示是no image。请问该如何解决呢？
![2021-08-04 15-53-24 的屏幕截图](https://user-images.githubusercontent.com/66103957/128146081-54cd692d-df6a-4379-9b8f-91fcbecd681f.png)
![2021-08-04 15-53-18 的屏幕截图](https://user-images.githubusercontent.com/66103957/128146099-480a1b47-6883-442b-8d3a-db198e981ff0.png)
![2021-08-04 15-53-59 的屏幕截图](https://user-images.githubusercontent.com/66103957/128146129-c7efc1e8-a3c1-4193-a025-ca7b022c5841.png)
![2021-08-04 15-54-07 的屏幕截图](https://user-images.githubusercontent.com/66103957/128146144-b96f8d8e-ee0c-4174-b320-f031e10c06e2.png)

**Comment by flynneva** [comment]
in order to run via `ros2 run` make sure you use the full name of the executable:

```
ros2 run usb_cam usb_cam_node_exe
```

just tried it on my machine and it was working as expected.

**Comment by flynneva** [comment]
ive just updated the `README.md`....apologies that it wasnt up-to-date!!!!

**Comment by hxj0316** [comment]
Hello, I just tried the method you mentioned, but it still shows the error as shown in the figure, and no camera image comes out。
![2021-08-05 09-17-10 的屏幕截图](https://user-images.githubusercontent.com/66103957/128276511-03cf4935-4834-460c-9cd1-ef3252ad75b5.png)

**Comment by flynneva** [comment]
for rviz2 make sure you set your fixed frame correctly, the default is "default_cam"

**Comment by hxj0316** [comment]
Thank you very much. After I modified it, he worked, but the screen has ghosting. Where should I go to modify it to make the screen clear?
![Uploading 2021-08-05 09-53-20 的屏幕截图.png…]()

**Comment by hxj0316** [comment]
Thank you very much. After I modified it, he worked, but the screen has ghosting. Where should I go to modify it to make the screen clear?
![2021-08-05 09-53-20 的屏幕截图](https://user-images.githubusercontent.com/66103957/128281080-33af163a-4e0b-434a-b61c-4e4a4983897e.png)

**Comment by flynneva** [comment]
I'd recommend trying to change the io method parameter or the format parameter.

I think the node should list out the possible values your device supports to the console.

**Comment by hxj0316** [comment]
Okay thank you. I would also like to ask how to achieve image compression in ros2? Because I found the picture is very stuck now. There are compressed topics in ros1, how to implement ros2?

**Comment by flynneva** [comment]
I think you can do this by following the instructions for compression for a similar package to this one

https://gitlab.com/boldhearts/ros2_v4l2_camera

**Comment by flynneva** [comment]
If you figure it out maybe make a PR back to this repo?

**Comment by hxj0316** [comment]
Okay, your answer helped me a lot, thank you very much, I will contact you if I will not follow up. thanks

**Comment by flynneva** [comment]
closing this issue since it seems like you're issue is solved. feel free to open another one if you run into more issues!
