### ISSUE TITLE
Camera calibration file / unknown control 'focus_auto'

### ISSUE THREAD

**Issue by Petros626** [ros-drivers/usb_cam#187]
Hey,

I succesfully run the camera, but there still two messages I'm unsure about. Where can I set the auto_focus found it in source code, but there's no param to set in launch file. Furthermore is the calibration needed? Where can I get it?

![Screenshot from 2022-05-18 08-27-49](https://user-images.githubusercontent.com/62354721/168972572-8476c757-7f7e-4178-a2c3-fb076a1c9b72.png)

Thanks for support

**Comment by flynneva** [comment]
Closing since I think this is resolved
