### ISSUE TITLE
Change QoS Settings

### ISSUE THREAD

**Issue by kalle264** [ros-drivers/usb_cam#194]
Hi,
I'm trying the change the reliability policy to best-effort on ros2-foxy.
Using
`--ros-args -p reliability:=best_effort `
is not working for me, which works fine with other nodes.

Is there any way to change it?

Thanks

**Comment by bvsam** [comment]
Hi. Is there any update on this issue? I'm also interested in changing QoS for the topics being published to by `usb_cam_node_exe` (such as `/image_raw`), but this package doesn't seem to support QoS overrides. I would be willing to look into the code required and submit a small PR if that's acceptable.
