### ISSUE TITLE
Multiple camera issue

### ISSUE THREAD

**Issue by Genozen** [ros-drivers/usb_cam#195]
Hello, we were able to visualize one camera in Rviz, but the other camera displays "no image".
![image](https://user-images.githubusercontent.com/74474611/194418365-018167df-8628-401f-9460-33b32e2090e9.png)

The code we ran are these two, with specified path to the params...
```
ros2 run usb_cam usb_cam_node_exe --remap __ns:=/usb_cam_0 --params-file /path/to/usb_cam/config/params_0.yaml
ros2 run usb_cam usb_cam_node_exe --remap __ns:=/usb_cam_1 --params-file /path/to/usb_cam/config/params_1.yaml
```

When echoing each topic, we realized that whichever node runs first gets to populate the image, while the later one does not.

We tried duplicating the params.yaml and map them to duplicated camera_info.yaml file as well, but no veil.

**Comment by flynneva** [comment]
@Genozen thabks for reporting this! Are you able to share the params files you used for both cameras?

Also, are you able to test that both cameras are available and can run at the same time without usb_cam in the picture? (e.g. with some SDK example or another tool)

I'll take a look at this over the weekend

**Comment by twdragon** [comment]
@flynneva is this issue still actual?

**Comment by flynneva** [comment]
@twdragon i never received a response from the original author and I don't have two cameras to test this on...so unfortunately I don't know 😅

**Comment by twdragon** [comment]
@flynneva thank you for your reply, I will close this issue now, so we will see if there are similar cases now.
