### ISSUE TITLE
multiple camera error issue

### ISSUE THREAD

**Issue by lantianhaohh** [ros-drivers/usb_cam#204]
The main log information is as follows:
[ INFO] [1668570097.003182938]: Starting 'head_camera' (/dev/video12) at 640x480 via mmap (yuyv) at 30 FPS
[ INFO] [1668570097.010430569]: using default calibration URL
[ INFO] [1668570097.013377280]: camera calibration URL: file:///home/firefly/.ros/camera_info/head_camera.yaml
[ INFO] [1668570097.013526031]: Unable to open camera calibration file [/home/firefly/.ros/camera_info/head_camera.yaml]
[ WARN] [1668570097.013571531]: Camera calibration file /home/firefly/.ros/camera_info/head_camera.yaml not found.
[ INFO] [1668570097.013614114]: Starting 'head_camera' (/dev/video14) at 640x480 via mmap (yuyv) at 30 FPS
[ERROR] [1668570097.097719481]: VIDIOC_STREAMON error 28, No space left on device
[ WARN] [1668570097.187234979]: unknown control 'focus_auto'

[camera1/usb_cam-2] process has died [pid 9882, exit code 1, cmd /home/firefly/catkin_ws/devel/lib/usb_cam/usb_cam_node __name:=usb_cam __log:=/home/firefly/.ros/log/9195338c-6560-11ed-870d-102c6bfd0978/camera1-usb_cam-2.log].
log file: /home/firefly/.ros/log/9195338c-6560-11ed-870d-102c6bfd0978/camera1-usb_cam-2*.log

the main error reporting problem is:VIDIOC_STREAMON error 28, No space left on device.

when both cameras are turned on,the usb_test.launch file is configured as follows:

```
<launch>
<arg name="dev1"                        default="/dev/video16"/> 
<arg name="dev2"                        default="/dev/video12"/>
<arg name="dev3"                        default="/dev/video14"/>
<group ns="camera1">  
  <node name="usb_cam" pkg="usb_cam" type="usb_cam_node" output="screen" >
    <param name="video_device" value="$(arg  dev2)" />
    <param name="image_width" value="640" />
    <param name="image_height" value="480" />
    <param name="pixel_format" value="yuyv" />
    <param name="color_format" value="yuv422p" />
    <param name="camera_frame_id" value="usb_cam" />
    <param name="io_method" value="mmap"/>
  </node>
  <node name="image_view" pkg="image_view" type="image_view" respawn="false" output="screen">
    <remap from="image" to="/usb_cam/image_raw"/>
    <param name="autosize" value="true" />
  </node>
   </group>
   <group ns="camera2">
  <node name="usb_cam" pkg="usb_cam" type="usb_cam_node" output="screen" >
    <param name="video_device" value="$(arg  dev3)" />
    <param name="image_width" value="640" />
    <param name="image_height" value="480" />
    <param name="pixel_format" value="yuyv" />
    <param name="color_format" value="yuv422p" />
    <param name="camera_frame_id" value="usb_cam" />
    <param name="io_method" value="mmap"/>
  </node>
  <node name="image_view" pkg="image_view" type="image_view" respawn="false" output="screen">
    <remap from="image" to="/usb_cam/image_raw"/>
    <param name="autosize" value="true" />
  </node>
   </group>
</launch>
```

**Comment by lantianhaohh** [comment]
Thank you!

**Comment by twdragon** [comment]
Closed as the author did not respond
