### ISSUE TITLE
Memory leak in develop branch, in  UsbCam::mjpeg2rgb()

### ISSUE THREAD

**Issue by AIRCAP** [ros-drivers/usb_cam#211]
https://github.com/ros-drivers/usb_cam/blob/develop/src/usb_cam.cpp line# 501

Calling both `av_new_packet() `and `av_packet_from_data()` allocates the buffer within `avpkt.buf` twice, causing usb_cam to run out of memory.

Possible solution: call `av_init_packet(&avpkt)` instead of `av_new_packet(&avpkt, len)`  which does not initialize this buffer, then call `av_packet_from_data()` which does.

Not making a pull request, since this is in process of refactoring anyway.

**Comment by twdragon** [comment]
@AIRCAP thank you for pointing this! Will be considered in refactoring

**Comment by flynneva** [comment]
@twdragon this seems to only be an issue on the ROS 1 `develop` branch...since I think the calls referenced here have been replaced with something else.  Might be something that @AIRCAP could confirm though...

**Comment by twdragon** [comment]
@flynneva you are right, this is only a ROS1 issue and will be refactored. I hope to start active rewriting before Christmas
