### ISSUE TITLE
Devices not supported by usb_cam?

### ISSUE THREAD

**Issue by testing715** [ros-drivers/usb_cam#220]
I have 3 cameras in 3 different models. They are intel realsense, insta 360 X2 and luxonis depthAI. The intel realsense one works well but the remaining two are not even in the device list. I checked by v4l2-ctl --list-devices and ls /dev/video* . They are not listed and cannot be detected. May I ask how to solve this problem?

Many thanks!

**Comment by flynneva** [comment]
@testing715 if the devices aren't V4L devices then they might not be supported. I'd suggest reaching out to the device manufacturer to determine if they do in fact support V4L or require some other SDK.
