### ISSUE TITLE
I[mjpeg @ 0x55ef0dff2880] No JPEG data found in image [ERROR] [1617870445.370329607]: Error while decoding frame.

### ISSUE THREAD

**Issue by devesh4424** [ros-drivers/usb_cam#223]

**Comment by twdragon** [comment]
@devesh4424 please provide the setup description and parameters of your node, otherwise, the issue should be considered useless.

**Comment by devesh4424** [comment]
I am using Ubuntu on VMware.
Parameters of node are width -1280 height -720
frame rate - 60fps

**Comment by twdragon** [comment]
@devesh4424 what is the pixel format? It seems you try to decode MJPEG from the camera that does not support it

**Comment by devesh4424** [comment]
I don't know the pixel format

**Comment by twdragon** [comment]
@devesh4424 try to experiment with different values for `pixel_format` parameter
