### ISSUE TITLE
Calibrtation issue ( No change in output before and after the calibration)

### ISSUE THREAD

**Issue by SunilSrivatsav9** [ros-drivers/usb_cam#249]
I am trying to calibrate my camera using ROS ( https://wiki.ros.org/camera_calibration) 
I have saved the calibration files and tried adding in the launch file of usb_cam. I used image_view to visualize the output of the camera stream. But the output is same before and after adding the calibration file. The distortion remains the same. I can see the change (distortion corrected) when clicking calibrate button after taking enough images for calibration however using calibration file in launch file seems to not effect the output. Let me know what I am missing.

**My calibration file:**
image_width: 640
image_height: 480
camera_name: usb_cam
camera_matrix:
  rows: 3
  cols: 3
  data: [193.36241,  -1.71276, 320.31501,
           0.     , 194.63608, 237.69045,
           0.     ,   0.     ,   1.     ]
distortion_model: equidistant
distortion_coefficients:
  rows: 1
  cols: 4
  data: [0.108415, -0.865421, 1.285079, -0.412555]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [193.36241,  -1.71276, 320.31501,   0.     ,
           0.     , 194.63608, 237.69045,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]

**My launch file:** 
`<launch>`
  `<node name="usb_cam" pkg="usb_cam" type="usb_cam_node" output="screen" >`
   ` <param name="video_device" value="/dev/video2" />`
    `<param name="image_width" value="640" />`
    `<param name="image_height" value="480" />`
    `<param name="pixel_format" value="yuyv" />`
  `<param name="camera_info_url" value="file:///home/sunilsrivatsav/Desktop/calibration/fisheye_micron/calibrationdata/ost.yaml" />`
    `<param name="camera_frame_id" value="usb_cam" />` 
    `<param name="io_method" value="mmap"/>`
  `</node>`
  `<node name="image_view" pkg="image_view" type="image_view" respawn="true" output="screen">`
    `<remap from="image" to="/usb_cam/image_raw"/>`
    `<param name="autosize" value="true" />`
  `</node>`
`</launch>`

**Comment by twdragon** [comment]
You should use [`image_proc`](http://wiki.ros.org/image_proc) to obtain and visualize truly rectified images. The issue will be now closed as it is not project-related.
