### ISSUE TITLE
Invoking "make -j2 -l2" failed

### ISSUE THREAD

**Issue by MARHEM602** [ros-drivers/usb_cam#252]
Hello, I have a problem with the package. I can gitclone the package but I have this problem when I catkin_make my work area.
I'm on Ros melodic on ubuntu 18.04 on linux. 
Thanks in advance 

![image](https://github.com/ros-drivers/usb_cam/assets/116814244/6077e98c-70c3-464e-8229-95f2fc55c9d0)

**Comment by twdragon** [comment]
@MARHEM602 you are compiling your workspace using by default a C++11 compiler. [`std::make_unique` is implemented in STL for C++14](https://stackoverflow.com/questions/24609271/errormake-unique-is-not-a-member-of-std). Try to add `-DCMAKE_CXX_FLAGS="-std=c++14"` in your invocation or use a newer compiler.

**Comment by MARHEM602** [comment]
I updated my G++ and ran the command :
catkin_make -DCMAKE_CXX_FLAGS="-std=c++14"

But I still have the same problem

**Comment by twdragon** [comment]
Incremental compiling prevents changing the standard. Try to remove `build` and `devel` subdirectories and recompile the entire workspace

**Comment by MARHEM602** [comment]
![image](https://github.com/ros-drivers/usb_cam/assets/116814244/b84a1f08-12a5-42ae-adec-28836c735f8f)
I'm going to update Opencv, I'll contact you as soon as I'm done. Thank you
