### ISSUE TITLE
invalid pointer

### ISSUE THREAD

**Issue by Narek-939** [ros-drivers/usb_cam#274]
[INFO] [launch]: All log files can be found below /home/vis/.ros/log/2023-08-15-21-27-35-910267-vis-Z590-D-95045
[INFO] [launch]: Default logging verbosity is set to INFO
/home/vis/Desktop/cam/install/usb_cam/share/usb_cam/config/params_1.yaml
[INFO] [usb_cam_node_exe-1]: process started with pid [95046]
[INFO] [show_image.py-2]: process started with pid [95048]
[usb_cam_node_exe-1] [INFO] [1692120456.064841763] [usb_cam]: camera_name value: test_camera
[usb_cam_node_exe-1] [WARN] [1692120456.064921117] [usb_cam]: framerate: 30.000000
[usb_cam_node_exe-1] [INFO] [1692120456.065972218] [usb_cam]: camera calibration URL: package://usb_cam/config/camera_info.yaml
[usb_cam_node_exe-1] [INFO] [1692120456.066341856] [usb_cam]: Starting 'test_camera' (/dev/video0) at 1920x1080 via mmap (mjpeg2rgb) at 30 FPS
[usb_cam_node_exe-1] [INFO] [1692120456.182394506] [usb_cam]: This devices supproted formats:
[usb_cam_node_exe-1] [INFO] [1692120456.182518988] [usb_cam]: 	Motion-JPEG: 1920 x 1080 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182526842] [usb_cam]: 	Motion-JPEG: 1920 x 1080 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182530764] [usb_cam]: 	Motion-JPEG: 1280 x 720 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182534342] [usb_cam]: 	Motion-JPEG: 960 x 540 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182537549] [usb_cam]: 	Motion-JPEG: 640 x 360 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182540552] [usb_cam]: 	Motion-JPEG: 640 x 480 (54 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182543538] [usb_cam]: 	Motion-JPEG: 800 x 600 (54 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182546908] [usb_cam]: 	Motion-JPEG: 1024 x 768 (54 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182549867] [usb_cam]: 	Motion-JPEG: 1280 x 960 (54 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182552914] [usb_cam]: 	Motion-JPEG: 1600 x 1200 (54 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182586956] [usb_cam]: 	Motion-JPEG: 1920 x 1080 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182590304] [usb_cam]: 	Motion-JPEG: 1920 x 1080 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182593376] [usb_cam]: 	YUYV 4:2:2: 1920 x 1080 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182596436] [usb_cam]: 	YUYV 4:2:2: 1920 x 1080 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182599559] [usb_cam]: 	YUYV 4:2:2: 1280 x 720 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182602748] [usb_cam]: 	YUYV 4:2:2: 960 x 540 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182605950] [usb_cam]: 	YUYV 4:2:2: 640 x 360 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182609058] [usb_cam]: 	YUYV 4:2:2: 640 x 480 (54 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182612126] [usb_cam]: 	YUYV 4:2:2: 800 x 600 (54 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182615183] [usb_cam]: 	YUYV 4:2:2: 1024 x 768 (54 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182618240] [usb_cam]: 	YUYV 4:2:2: 1280 x 960 (54 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182621258] [usb_cam]: 	YUYV 4:2:2: 1600 x 1200 (54 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182624468] [usb_cam]: 	YUYV 4:2:2: 1920 x 1080 (60 Hz)
[usb_cam_node_exe-1] [INFO] [1692120456.182627711] [usb_cam]: 	YUYV 4:2:2: 1920 x 1080 (60 Hz)
[usb_cam_node_exe-1] unknown control 'white_balance_temperature_auto'
[usb_cam_node_exe-1] 
[usb_cam_node_exe-1] [INFO] [1692120456.184186976] [usb_cam]: Setting 'white_balance_temperature_auto' to 1
[usb_cam_node_exe-1] [INFO] [1692120456.184205567] [usb_cam]: Setting 'exposure_auto' to 3
[usb_cam_node_exe-1] unknown control 'exposure_auto'
[usb_cam_node_exe-1] 
[usb_cam_node_exe-1] [INFO] [1692120456.185539165] [usb_cam]: Setting 'focus_auto' to 0
[usb_cam_node_exe-1] unknown control 'focus_auto'
[usb_cam_node_exe-1] 
[usb_cam_node_exe-1] [INFO] [1692120456.188846173] [usb_cam]: Timer triggering every 33 ms
[usb_cam_node_exe-1] free(): invalid pointer
[ERROR] [usb_cam_node_exe-1]: process has died [pid 95046, exit code -6, cmd '/home/vis/Desktop/cam/install/usb_cam/lib/usb_cam/usb_cam_node_exe --ros-args -r __node:=usb_cam --params-file /home/vis/Desktop/cam/install/usb_cam/share/usb_cam/config/params_1.yaml'].

I compiled this command 
ros2 launch usb_cam demo_launch.py

**Comment by TZECHIN6** [comment]
I dont know why, but I am also encounter this issue. The quick way to fix it is to not using `mjpeg2rgb`, yes I know although it says the camera pixel_format is supported...

**Comment by flynneva** [comment]
@Narek-939 @TZECHIN6 on it! Sorry this was a result of my latest work on trying to address some memory leaks

**Comment by TZECHIN6** [comment]
@flynneva take your time. I appreciate your work to the community :D

**Comment by Narek-939** [comment]
@flynneva @TZECHIN6 thanks)

**Comment by Narek-939** [comment]
I will look forward to fixing this issue)

**Comment by flynneva** [comment]
The invalid pointer issue should be fixed now on the `ros2` branch. Going to close this issue, feel free to open more if you run into anything else!
