### ISSUE TITLE
cannot find demo_launch.py

### ISSUE THREAD

**Issue by TZECHIN6** [ros-drivers/usb_cam#277]
I might miss something important... but I couldn't find any launch file named demo_launch.py

I am working on ros2 branch. I would be appreciate to anyone who could direct me to that file.

**Comment by flynneva** [comment]
@TZECHIN6 we renamed it to `camera.launch.py` I think after #248. I'll update the docs to reflect the name change 👍🏼

**Comment by TZECHIN6** [comment]
Thanks. now its clear~
