### ISSUE TITLE
Cannot create a file handler for V4L device '/dev/video0'

### ISSUE THREAD

**Issue by yeyanan93** [ros-drivers/usb_cam#280]
![Screenshot from 2023-08-26 15-45-35](https://github.com/ros-drivers/usb_cam/assets/48683431/7dd0b9c4-cec4-4685-b051-466f574302a9)

**Comment by flynneva** [comment]
@yeyanan93 does the video device "/dev/video0" exist on your system? It might be called something else.

**Comment by yeyanan93** [comment]
@flynneva yes, the following code can solve the problem.
`sudo chmod 777 /dev/video0`

**Comment by flynneva** [comment]
@yeyanan93 I'll go ahead and close this issue then - glad you got it fixed!
