### ISSUE TITLE
Framerate lower than demanded on rasp pi csi camera with usb_cam_test launch file

### ISSUE THREAD

**Issue by YikaiZengTUD** [ros-drivers/usb_cam#281]
HI, 

When I implement the packaege in a Raspberry Pi (both 3B and 4B). The /usb_cam/image_raw updates only about 7-8Hz when asking for a 30 fps using the usb_cam_test.launch. The same set of hardware (csi camera + the pi) has sucessful publish 30 fps image topic with other driver (like uvc_camera), whichi I believe cross out the problem of the hardware. After all 30 fps is very mild requirement for most cameras.

**Comment by flynneva** [comment]
@YikaiZengTUD is this for ROS 1? This is probably related to [the known  timestamp issue](https://github.com/ros-drivers/usb_cam/issues/278) that is going to be fixed [after this PR](https://github.com/ros-drivers/usb_cam/pull/272)

**Comment by YikaiZengTUD** [comment]
Hi @flynneva, I don't encounter the jump in timestamps as suggested in the other issue. It is a ROS on a Raspberry. I found some more facts about it. 
Here is an output from the test script when running the usb_cam-test.launch

> [INFO] [1693472957.289775]: now: 1693472957.2896478, Received timestamp: 1693472957.075725, diff: 0.21393489837646484
> [INFO] [1693472957.401565]: now: 1693472957.4014425, Received timestamp: 1693472957.2091763, diff: 0.1922757625579834
> [INFO] [1693472957.491541]: now: 1693472957.4913723, Received timestamp: 1693472957.342499, diff: 0.14888453483581543
> [INFO] [1693472957.584868]: now: 1693472957.584713, Received timestamp: 1693472957.4092045, diff: 0.17551946640014648
> [INFO] [1693472957.676409]: now: 1693472957.6762583, Received timestamp: 1693472957.4757357, diff: 0.20053529739379883
> [INFO] [1693472957.761797]: now: 1693472957.7616532, Received timestamp: 1693472957.5757284, diff: 0.18593740463256836
> [INFO] [1693472957.845582]: now: 1693472957.8454173, Received timestamp: 1693472957.675934, diff: 0.1694955825805664

Which is only about 5-6Hz than the desired 30Hz. Just to FYI, the compressed image updates at 30Hz, at least the topic gets published at a proper frequency.

I also repeated the simple process on a virtual machine in the laptop, the /usb_cam/image_raw updates at 30Hz as expected

I also tried to check if this is about the hardware. Tried on two different rasp pi (3B+ and 4B), and two different cameras but all went through the csi port. Nothing really changes.

I also run a [uvc-camera ](http://wiki.ros.org/uvc_camera) node, which successfully updates the /image_raw at 30 fps, so I believe there is no bottleneck in hardware.

Not sure if you can somehow reproduce the problem and it would be nice if you have some suggestions on showing more nature of it. Is there a way that I should be able to force a 30fps topic to publish?
