### ISSUE TITLE
Node exits because of pixel formatting issues？

### ISSUE THREAD

**Issue by zymouse** [ros-drivers/usb_cam#308]
- [x] branch: ros2
- [x] commit: f5d3e5be625ccae17019d85a27a9c1304819d00a

@flynneva 
`v4l2-ctl --device=/dev/video0 --all`
<img width="673" alt="image" src="https://github.com/ros-drivers/usb_cam/assets/46778435/89bdfb87-0d6a-48b8-a614-2a477f893a26">
Because of a camera firmware error, the pixel format is actually `uyvy`.

When I use the correct pixel format `uyvy`, the usb_cam node exits incorrectly
<img width="1358" alt="image" src="https://github.com/ros-drivers/usb_cam/assets/46778435/b6b71d49-cfa4-491b-8277-0a33bffa4455">

**Comment by flynneva** [comment]
@zymouse so are you asking for an option to "skip" the check and continue on with the selected format?

I guess that can be added.

**Comment by zymouse** [comment]
@flynneva 
Thank you very much for your answer: the option to "skip" the check and continue with the selected format, can you tell me how to change it in the code?

**Comment by flynneva** [comment]
@zymouse we'd have to add it still, but essentially it would include adding a new parameter to the yaml file, declaring and setting the parameter in the cpp code and then checking that bool within the new format validation logic we have now.

I can add this maybe over the weekend if I find some time, if not this weekend next week 👍

**Comment by zymouse** [comment]
@flynneva Good afternoon, did this issue, get resolved? Thank you very much.

**Comment by flynneva** [comment]
@zymouse hey hey! Not yet but I'll take a look this weekend. Sorry it's been a busy start to the new year

**Comment by flynneva** [comment]
@zymouse can you try out this branch: https://github.com/ros-drivers/usb_cam/pull/317

and set the new parameter `skip_format_check` to `true` for your hardware and sees if it fixes your issue?

**Comment by flynneva** [comment]
@zymouse so to support your buggy camera you'll need the branch from #317 and also to modify [this line](https://github.com/ros-drivers/usb_cam/blob/ros2/src/usb_cam.cpp#L435) to:

```diff
- m_image.v4l2_fmt.fmt.pix.pixelformat = m_image.pixel_format->v4l2();
+m_image.v4l2_fmt.fmt.pix.pixelformat = V4L2_PIX_FMT_YUYV;
```

Try that out and let me know how it goes

**Comment by zymouse** [comment]
Okay. Thank you very much.

**Comment by flynneva** [comment]
Closing as complete / wont fix on the main line here since it is such a unique problem
