### ISSUE TITLE
where is camera_info_manager.hpp

### ISSUE THREAD

**Issue by iplayfast** [ros-drivers/usb_cam#322]
in include/usb_cam/usb_cam_node it has the following line 

#include "camera_info_manager/camera_info_manager.hpp"

Where is this file?

**Comment by flynneva** [comment]
@iplayfast it comes from the camera_info_manager package, in a different repository. That's how ROS is structured...completely distributed.

https://github.com/ros-perception/image_common/blob/rolling/camera_info_manager/include/camera_info_manager/camera_info_manager.hpp
