### ISSUE TITLE
in ros2 jazzy,I get a new topic '.../zstd' through this package,recommand to use?

### ISSUE THREAD

**Issue by marcuswuh** [ros-drivers/usb_cam#340]
I can not find any info on the topic

**Comment by knorth55** [comment]
`zstd` comes from `zstd_image_transport` in `image_transport_plugins`.
https://github.com/ros-perception/image_transport_plugins

It uses `zstd` format to send images in compressed format.
If you want to use the compression, the tutorial page may be useful.
https://github.com/ros-perception/image_transport_tutorials

**Comment by knorth55** [comment]
I will close this issue, because it is not related to this repo.
