### ISSUE TITLE
segmentation fault on hydro 

### ISSUE THREAD

**Issue by Exception4U** [ros-drivers/usb_cam#41]
[ 50%] Building CXX object usb_cam/CMakeFiles/usb_cam.dir/src/usb_cam.cpp.o
c++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See file:///usr/share/doc/gcc-4.6/README.Bugs for instructions.
make[2]: **\* [usb_cam/CMakeFiles/usb_cam.dir/src/usb_cam.cpp.o] Error 4
make[1]: **\* [usb_cam/CMakeFiles/usb_cam.dir/all] Error 2
make: **\* [all] Error 2
Invoking "make" failed
rushi@rushi-pc:ros_ws$ catkin_make -DCATKIN_WHITELIST_PACKAGES=usb_cam >>error.txt
c++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See file:///usr/share/doc/gcc-4.6/README.Bugs for instructions.
make[2]: **\* [usb_cam/CMakeFiles/usb_cam.dir/src/usb_cam.cpp.o] Error 4
make[1]: **\* [usb_cam/CMakeFiles/usb_cam.dir/all] Error 2
make: **\* [all] Error 2
Invoking "make" failed

**Comment by rctoris** [comment]
What distro/version are you compiling on?

**Comment by Exception4U** [comment]
i am compiling it on Hydro

**Comment by rctoris** [comment]
I meant operating system.

**Comment by Exception4U** [comment]
Ubuntu 12.04

**Comment by twdragon** [comment]
Closed for inactivity for 7 years. Actually, this issue should not be considered in the context of the maintenance of this package.
