### ISSUE TITLE
Published topics are a bit wonky

### ISSUE THREAD

**Issue by jonbinney** [ros-drivers/usb_cam#42]
The ROS wiki ( http://wiki.ros.org/usb_cam ) says that images will be published on `~<camera_name>/image`, when in fact they will be published on `~/image_raw` (the camera_name parameter is not used at all for the topics).

It's also a bit odd to use a private node handle for advertising topics. The more common thing to do is to use public node handles for publishing/subscribing, and to use private node handles for reading parameters. Then if people want to put the topics into a namespace, they can use the `ns="foo"` attribute in the node element in the launchfile.

**Comment by twdragon** [comment]
Closed due to inactivity and lack of users'interest.
