### ISSUE TITLE
Is there something wrong with the exposure?

### ISSUE THREAD

**Issue by Chen-Xieyuanli** [ros-drivers/usb_cam#47]
PARAMETERS
- /image_view/autosize: True
- /rosdistro: indigo
- /rosversion: 1.11.16
- /usb_cam/auto_white_balance: True
- /usb_cam/autoexposure: True
- /usb_cam/camera_frame_id: usb_cam
- /usb_cam/image_height: 480
- /usb_cam/image_width: 640
- /usb_cam/io_method: mmap
- /usb_cam/pixel_format: mjpeg
- /usb_cam/video_device: /dev/video0

NODES
  /
    image_view (image_view/image_view)
    usb_cam (usb_cam/usb_cam_node)

auto-starting new master
process[master]: started with pid [20414]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to d4a0e2a6-e04d-11e5-be96-5cc5d4b62664
process[rosout-1]: started with pid [20427]
started core service [/rosout]
/opt/ros/indigo/lib/python2.7/dist-packages/roslib/packages.py:447: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if resource_name in files:
process[usb_cam-2]: started with pid [20430]
process[image_view-3]: started with pid [20440]
[ INFO] [1456906059.308717716]: Using transport "raw"
[ INFO] [1456906059.523110174]: using default calibration URL
[ INFO] [1456906059.523191021]: camera calibration URL: file:///home/chenxieyuanli/.ros/camera_info/head_camera.yaml
[ INFO] [1456906059.523240698]: Unable to open camera calibration file [/home/chenxieyuanli/.ros/camera_info/head_camera.yaml]
[ WARN] [1456906059.523276190]: Camera calibration file /home/chenxieyuanli/.ros/camera_info/head_camera.yaml not found.
[ INFO] [1456906059.523294680]: Starting 'head_camera' (/dev/video0) at 640x480 via mmap (mjpeg) at 30 FPS
[ WARN] [1456906059.926171118]: unknown control 'focus_auto'

![Uploading 2016-3-2.png…]()

![Uploading 2016-3-2.gif…]()
![Uploading 2016-3-2.png…]()

**Comment by JamesChenxie** [comment]
![Uploading 2016-3-2.gif…]()

**Comment by JamesChenxie** [comment]
Why can't I upload the picture?

![Uploading 2016-3-2.png…]()
