### ISSUE TITLE
nodelet support

### ISSUE THREAD

**Issue by k-okada** [ros-drivers/usb_cam#49]
uvc_camera and libuvc_camera had nodelet support, i think usb_cam should have this too, as this is the "standard" usb camera driver for ROS

**Comment by ledmonster** [comment]
Here is a PR to support nodelet. pull request #59

**Comment by skohlbr** [comment]
Another one here: #78. 

And another implementation in a commit here: https://github.com/Intermodalics/usb_cam/commit/9f043cca33c32c3fb4083a9751fe83237d799843

**Comment by twdragon** [comment]
Closing in favour of consideration of #78
