### ISSUE TITLE
Image is not stable 

### ISSUE THREAD

**Issue by Tom-Shen** [ros-drivers/usb_cam#50]
My environment is raspberry Pi 3, indigo, Logitec Quickcam

when I run the usb_cam, I can get the image, but it is not stable, I got error like below:
# 

[swscaler @ 0xd56ca0] No accelerated colorspace conversion found from yuv422p to rgb24.
[mjpeg @ 0xd758a0] mjpeg_decode_dc: bad vlc: 0:0 (0xd75e68)
[mjpeg @ 0xd758a0] error dc
# [mjpeg @ 0xd758a0] error y=59 x=34

**Comment by LucasMahieu** [comment]
i have the same problem, did some one find any solution ?
