### ISSUE TITLE
Invalid camera calibration URL

### ISSUE THREAD

**Issue by libing64** [ros-drivers/usb_cam#52]
After calibrating my camera using camera_calibration, I saved the calibration file.

The calibration file - Gsou.yaml looks like this:

[Gsou.yaml.txt](https://github.com/bosch-ros-pkg/usb_cam/files/278701/Gsou.yaml.txt)

Then I restart the usb_camera:
[usb_cam.launch.txt](https://github.com/bosch-ros-pkg/usb_cam/files/278702/usb_cam.launch.txt)

However, it always says, 'Invalid camera calibration URL: home/xx/catkin_ws/src/usb_cam/param/Gsou.yaml', is there anything wrong? please provide some help, thansk.

**Comment by fherreroc** [comment]
True. I needed to add "file://" to the beginning of the camera_info_url parameter value, then it works.

**Comment by keithicus** [comment]
I had the same problem, the following worked for me:

<param name="camera_info_url" value="package://my_usb_cam_launcher/calibration/myUSBCameraCalibrationFile.yaml"/>

**Comment by bigbellmercy** [comment]
> True. I needed to add "file://" to the beginning of the camera_info_url parameter value, then it works.

By using the solution above, the following worked for me:

`<param name="camera_info_url" value="file:///home/user_name/the_folder_path/camera.yaml"`

Here, the slash(/) should be used **triple times like '///'** instead of two times like '//'.
