### ISSUE TITLE
Node doesn't shutdown when SIGINT -2 kill is received

### ISSUE THREAD

**Issue by dgitz** [ros-drivers/usb_cam#61]
On Raspberry Pi, when node is run, killed with a Ctrl-C and then re-ran, gives the following error:  VIDIOC_S_FMT error 5, Input/output error  because node doesn't release video device since a.spin() never returns.  Requires restarting the Raspberry pi before node can be run again.

**Comment by pudumula** [comment]
Hi @dgitz try restarting roscore after Ctrl-C.
Can you post the result of this operation ?
