### ISSUE TITLE
[mjpeg @ 0x1071e00] Changeing bps to 8 and [swscaler @ 0x1080d60] deprecated pixel format used, make sure you did set range correctly

### ISSUE THREAD

**Issue by lhzlhz** [ros-drivers/usb_cam#80]
Set "pixel_format=mjpeg" in Ubunt16.04 & ROS-Kinetic, then run the usb_cam.The terminal show:
![image](https://user-images.githubusercontent.com/32038764/32698215-8fcd55c4-c7dc-11e7-83f3-2675c2dbf2c3.png)
Why the bps change form 30 to 8?
Why  show "deprecated pixel format used, make sure you did set range correctly"?

**Comment by vannem95** [comment]
I don't get the calibration file not found warning but i do get the bit rate message. Also it says 30 fps but the average rate (found using rostopic hz) ranges from 12 hz to 0.5 hz. Sometimes all of a sudden the fps increases to 20-25 and sometimes i get the select timeout error and the process is terminated. Anyone able to solve this issue?

**Comment by lhzlhz** [comment]
Try run a ubuntu not install in the virtual machine.

**Comment by Damowerko** [comment]
The problem persists when doing a native install.

**Comment by henryng375** [comment]
Did anyone solve this problem?

**Comment by jptalledo10** [comment]
Having the same problem with a USB Camera. Checking if there is a fix or a workaround for this

**Comment by lhzlhz** [comment]
Run the usb_cam not in a virtual machine, then everthing is ok.

**Comment by smallpigg** [comment]
Same problem, did anyone solve this problem? I have not run it in virtual machine.

**Comment by lhzlhz** [comment]
Do you use USB2.0 for the camera? You can try for the USB3.0. If it doesn't work, you can show the terminal information to us.

**Comment by lhzlhz** [comment]
> Same problem, did anyone solve this problem? I have not run it in virtual machine.

Do you use USB2.0 for the camera? You can try for the USB3.0. If it doesn't work, you can show the terminal information to us.

**Comment by smallpigg** [comment]
It was used a USB3.0 with blue color. Here are two screenshots.
![screenshot from 2019-02-13 21-44-55](https://user-images.githubusercontent.com/13197043/52717217-92474b80-2fdb-11e9-9cfb-875d0691599b.png)
![screenshot from 2019-02-13 22-03-40](https://user-images.githubusercontent.com/13197043/52717222-96736900-2fdb-11e9-9c1e-47e709026132.png)

**Comment by smallpigg** [comment]
launch file:

<launch>
  <node name="usb_cam" pkg="usb_cam" type="usb_cam_node" output="screen" >
    <param name="video_device" value="/dev/video1" />
    <param name="image_width" value="640" />
    <param name="image_height" value="480" />
    <param name="pixel_format" value="mjpeg" />
    <param name="camera_frame_id" value="usb_cam" />
    <param name="io_method" value="mmap"/>
  </node>
  <node name="image_view" pkg="image_view" type="image_view" respawn="false" output="screen">
    <remap from="image" to="/usb_cam/image_raw"/>
    <param name="autosize" value="true" />
  </node>
</launch>

**Comment by lhzlhz** [comment]
> Here is the launch file
> ![screenshot from 2019-02-13 22-11-17](https://user-images.githubusercontent.com/13197043/52717604-73958480-2fdc-11e9-99b4-2b5321a6aabf.png)

Modify "pixel_format" from "mjpeg" to "yuyv" in the launch file .

**Comment by smallpigg** [comment]
This is camera1, not camera0. And I have set 'yuyv' for camera1, it is not correct.  The camera0 works normally. Camera0 is integrated. But I want use camera1.

**Comment by lhzlhz** [comment]
> This is camera1, not camera0. And I have set 'yuyv' for camera1, it is not correct. The camera0 works normally. Camera0 is integrated. But I want use camera1.

The video show normal? If it work normal, you can ignore the information.
Or you can try like this [](https://answers.ros.org/question/217382/garbled-image-problem-on-usb_cam/)

**Comment by smallpigg** [comment]
Ok, the video shows normal. Thanke  you.

**Comment by lukehutch** [comment]
Setting `yuyv` as the format is not a good answer, if the camera natively outputs MJPEG, and you want to keep the video frames in compressed `mjpeg` format, e.g. for recording to a bag file.
