### ISSUE TITLE
Problem with <param name="pixel_format" value="mjpeg" />  

### ISSUE THREAD

**Issue by lamhung81** [ros-drivers/usb_cam#82]
Hi alls,
I tried to get video in mjpeg format, however, I always got

Webcam: expected picture but didn't get it...

If I put yuyv instead of mjpeg, it is ok.  

What can I do in order to got mjpeg format?

Any suggests or advices are well come. Thanks

**Comment by lamhung81** [comment]
In fact, by chan I got access to 
 ​https://github.com/withrobot/oCam/tree/master/Firmware/Update_FW
I tried to update firmware of my camera oCam-5CRO-U by oCam-5CRO-U_R1707_170629.img
Then it works!!!

**Comment by twdragon** [comment]
Closed due to inactivity
