### ISSUE TITLE
ROS Error USB_CAM not launching---Ubuntu 16.04

### ISSUE THREAD

**Issue by sharwanram** [ros-drivers/usb_cam#85]
~$ roslaunch /home/gpslab/catkin_wsorb/src/usb_cam/launch/usb_cam-test.launch
... logging to /home/gpslab/.ros/log/14c1bbda-6431-11e8-8ba2-b06ebf7e7a7d/roslaunch-gpslab-System-Product-Name-9465.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://gpslab-System-Product-Name:44395/

SUMMARY
========

PARAMETERS
 * /image_view/autosize: True
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
 * /usb_cam/camera_frame_id: usb_cam
 * /usb_cam/image_height: 480
 * /usb_cam/image_width: 640
 * /usb_cam/io_method: mmap
 * /usb_cam/pixel_format: yuyv
 * /usb_cam/video_device: /dev/video0

NODES
  /
    image_view (image_view/image_view)
    usb_cam (usb_cam/usb_cam_node)

ROS_MASTER_URI=http://localhost:11311

ERROR: cannot launch node of type [usb_cam/usb_cam_node]: usb_cam
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/opt/ros/kinetic/share
process[image_view-2]: started with pid [9482]
[ INFO] [1527703031.132855713]: Using transport "raw"

**Comment by Briandez** [comment]
You need to a add a source file in your bash.rc
OR
Open the following directory in the terminal **/home/gpslab/catkin_wsorb/**
and type the following command
>> source devel/setup.bash
On the same terminal cd to your launch directory i.e. **/home/gpslab/catkin_wsorb/src/usb_cam/launch/**
and roslaunch the file
>> roslaunch usb_cam-test.launch

**Comment by flynneva** [comment]
closing this issue since it looks like it was resolved @sharwanram
