### ISSUE TITLE
Catkin_make failure

### ISSUE THREAD

**Issue by henryng375** [ros-drivers/usb_cam#89]
I followed the step, But I get such error:
CMake Error at /opt/ros/indigo/share/catkin/cmake/assert.cmake:17 (message):
  

  Assertion failed: check for file existence, but filename
  (RT_LIBRARY-NOTFOUND) unset.  Message: RT Library

Call Stack (most recent call first):
  /opt/ros/indigo/share/catkin/cmake/tools/rt.cmake:42 (assert_file_exists)
  /opt/ros/indigo/share/catkin/cmake/all.cmake:147 (include)
  /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:52 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/darwin/work/ros_ws/usbcam_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/darwin/work/ros_ws/usbcam_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

What should I do?

**Comment by k-okada** [comment]
what is your OS and CPU? Debian + ARM64? Or Darwin on Mac? or normal Ubuntu?

**Comment by henryng375** [comment]
I used it in indigo of ubuntu.
I just solved this in the following solution.
Go to /opt/ros/indigo/share/catkin/cmake/tools/rt.cmake 
and Change from if(NOT (APPLE OR WIN32 OR MINGW OR ANDROID)) to if(NOT (APPLE OR WIN32 OR MINGW OR ANDROID OR UNIX))

**Comment by PierreExeter** [comment]
Thanks, this worked for me on Ubuntu 18.04 and ROS Melodic.

**Comment by twdragon** [comment]
Closed due to inactivity
