### ISSUE TITLE
high CPU usage

### ISSUE THREAD

**Issue by ghost** [ros-drivers/usb_cam#9]
Hello,
I'm running the usb_cam node on ODROID U3 (quad core 1.7GHz ARM, 2G RAM) with a Logitech C920. I noticed that this node by itself is using about 120% of CPU. Is it normal? Are there ways to optimize it? This is the launch file:

```
<launch>
<node name="camera" pkg="usb_cam" type="usb_cam_node" respawn="false" output="screen">
<param name="video_device" value="/dev/video0"/>
<param name="io_method" value="mmap"/>
<param name="image_width" value="640"/>
<param name="image_height" value="480"/>
<param name="color_mode" value="mono8"/>
<param name="pixel_format" value="yuyv"/>
</node>
</launch>
```

Thanks!

**Comment by tuloski** [comment]
Yeah, I have the same exact problem. Maybe it is the ODROID U3 CPU estimation that is bad?
I'm recording 800x600 @ 20fps

**Comment by mushroomgithub** [comment]
thank you very much!

**Comment by tuloski** [comment]
Finally I found a way to optimize it with the compiler.
Do "catkin_make --pkg usb_cam -DCMAKE_BUILD_TYPE=Release" to compile with optimization.
It is now running 800x600 @20 FPS with 25% CPU usage.

**Comment by flynneva** [comment]
closing this issue since its almost a decade old
