### ISSUE TITLE
usb_cam cannot run when the pixel format is rgb24.

### ISSUE THREAD

**Issue by hankewei** [ros-drivers/usb_cam#90]
usb_cam cannot run when the pixel format is rgb24.
terminal output is as follows.
Please help me find out why.

**roslaunch usb_cam usb_cam-test.launch** 
... logging to /home/nvidia/.ros/log/c21aa304-6d1f-11e8-b26d-00044b8d87aa/roslaunch-tegra-ubuntu-6800.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
WARNING: disk usage in log directory [/home/nvidia/.ros/log] is over 1GB.
It's recommended that you use the 'rosclean' command.

started roslaunch server http://tegra-ubuntu:33447/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
 * /usb_cam/camera_frame_id: usb_cam
 * /usb_cam/image_height: 720
 * /usb_cam/image_width: 1280
 * /usb_cam/io_method: mmap
 * /usb_cam/pixel_format: rgb24
 * /usb_cam/video_device: /dev/video0

NODES
  /
    usb_cam (usb_cam/usb_cam_node)

ROS_MASTER_URI=http://localhost:11311

process[usb_cam-1]: started with pid [6818]
[ INFO] [1528697923.327253730]: using default calibration URL
[ INFO] [1528697923.327804838]: camera calibration URL: file:///home/nvidia/.ros/camera_info/head_camera.yaml
[ INFO] [1528697923.328183784]: Unable to open camera calibration file [/home/nvidia/.ros/camera_info/head_camera.yaml]
[ WARN] [1528697923.328337065]: Camera calibration file /home/nvidia/.ros/camera_info/head_camera.yaml not found.
[ INFO] [1528697923.328510858]: **Starting 'head_camera' (/dev/video0) at 1280x720 via mmap (rgb24) at 30 FPS**
[ WARN] [1528697923.515465061]: unknown control 'white_balance_temperature_auto'

[usb_cam-1] **process has died [pid 6818, exit code -11**, cmd /home/nvidia/catkin_ws/devel/lib/usb_cam/usb_cam_node __name:=usb_cam __log:=/home/nvidia/.ros/log/c21aa304-6d1f-11e8-b26d-00044b8d87aa/usb_cam-1.log].
log file: /home/nvidia/.ros/log/c21aa304-6d1f-11e8-b26d-00044b8d87aa/usb_cam-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by twdragon** [comment]
Checking the introduction of the pixel format and proper memory management to utilize it. It is a definitely memory management error with improper pixel data input handling.

**Comment by flynneva** [comment]
Closing as inactive
