### ISSUE TITLE
Re-open failure with ELP-USB500W02M

### ISSUE THREAD

**Issue by drofp** [ros-drivers/usb_cam#94]
===Summary===
Opening camera with `roslaunch usb_cam usb_cam-test.launch` works, but after closing it, I cannot launch the launch file again successfully unless I unplug and re-plug in the camera I am using (ELP-USB500W02M).

===Details===
After attempting to launch the launch file the second time, the window appears as so:
![image](https://user-images.githubusercontent.com/23289001/42257089-bca0871c-7f09-11e8-9fc3-a5cb94dbd9be.png)

Here is the output, with an attempt to close with ctrl+c:
![image](https://user-images.githubusercontent.com/23289001/42257165-33e3d9a0-7f0a-11e8-90c9-39f714111613.png)
NOTE: The camera calibration file warning appears even when the camera view works (on the first attempt)

My launch file:
![image](https://user-images.githubusercontent.com/23289001/42257428-57561eba-7f0b-11e8-9462-c4de0aac8a42.png)

===System Info===
- Dell XPS 15 9560
- Ubuntu 16.04
- ROS Kinetic

**Comment by shoemakerlevy9** [comment]
Make sure that the previous ROS process has shutdown properly. Use ctrl+c to shutdown roslaunch if started from a terminal. Otherwise you can also use `killall roslaunch` and `killall roscore` so shutdown everything ROS related. Use the `ps -Alf | grep ROS` to make sure that no ros processes are still running.

**Comment by twdragon** [comment]
@drofp it means that the OS assigns new device link to the camera when you plug it again onto the bus. I think, you need an `udev` hack or another system-wide solution to handle this issue. Closed.
