### ISSUE TITLE
Melodic release please

### ISSUE THREAD

**Issue by doisyg** [ros-drivers/usb_cam#95]
Support for the current LTS would be nice!

**Comment by k-okada** [comment]
OK, done
https://github.com/ros/rosdistro/pull/18578

Please check when the deb binary is released.

ROS Orphaned Package Maintainer Team
http://wiki.ros.org/OrphanedPackage
https://github.com/orgs/ros-gbp/teams/ros-orphaned-packages

**Comment by doisyg** [comment]
Thanks!
